const now = () => new Date().toISOString();

export const demoVolunteers = [
  {
    id: 'vol-priya',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 98765 43210',
    skills: ['First Aid', 'Teaching', 'Counseling'],
    available: true,
    location: { lat: 19.076, lng: 72.8777 },
    createdAt: now(),
  },
  {
    id: 'vol-rahul',
    name: 'Rahul Patel',
    email: 'rahul@example.com',
    phone: '+91 98765 43211',
    skills: ['Cooking', 'Driving', 'First Aid'],
    available: true,
    location: { lat: 19.082, lng: 72.8812 },
    createdAt: now(),
  },
  {
    id: 'vol-ananya',
    name: 'Ananya Iyer',
    email: 'ananya@example.com',
    phone: '+91 98765 43212',
    skills: ['Teaching', 'Translation', 'Event Management'],
    available: true,
    location: { lat: 19.0596, lng: 72.8295 },
    createdAt: now(),
  },
  {
    id: 'vol-vikram',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    phone: '+91 98765 43213',
    skills: ['Construction', 'Driving', 'Heavy Lifting'],
    available: true,
    location: { lat: 19.0895, lng: 72.8656 },
    createdAt: now(),
  },
  {
    id: 'vol-meera',
    name: 'Meera Joshi',
    email: 'meera@example.com',
    phone: '+91 98765 43214',
    skills: ['Nursing', 'First Aid', 'Counseling'],
    available: false,
    location: { lat: 19.0728, lng: 72.8826 },
    createdAt: now(),
  },
  {
    id: 'vol-arjun',
    name: 'Arjun Nair',
    email: 'arjun@example.com',
    phone: '+91 98765 43215',
    skills: ['IT Support', 'Teaching', 'Photography'],
    available: true,
    location: { lat: 19.1136, lng: 72.8697 },
    createdAt: now(),
  },
];

export const demoTasks = [
  {
    id: 'task-medical-camp',
    title: 'Emergency Medical Camp',
    description: 'Set up and run a medical camp in Dharavi area for flood-affected families.',
    requiredSkills: ['First Aid', 'Nursing', 'Counseling'],
    urgency: 'high',
    status: 'pending',
    location: { lat: 19.0438, lng: 72.8534 },
    createdAt: now(),
  },
  {
    id: 'task-community-kitchen',
    title: 'Community Kitchen Setup',
    description: 'Organize and manage a community kitchen serving 500+ meals daily.',
    requiredSkills: ['Cooking', 'Event Management'],
    urgency: 'high',
    status: 'pending',
    location: { lat: 19.076, lng: 72.8777 },
    createdAt: now(),
  },
  {
    id: 'task-tutoring',
    title: 'School Tutoring Program',
    description: 'After-school tutoring for underprivileged children in Andheri.',
    requiredSkills: ['Teaching', 'Counseling'],
    urgency: 'medium',
    status: 'pending',
    location: { lat: 19.1197, lng: 72.8464 },
    createdAt: now(),
  },
  {
    id: 'task-shelter-repair',
    title: 'Shelter Repair Drive',
    description: 'Repair damaged shelters in coastal areas after recent storms.',
    requiredSkills: ['Construction', 'Heavy Lifting', 'Driving'],
    urgency: 'medium',
    status: 'pending',
    location: { lat: 19.0888, lng: 72.869 },
    createdAt: now(),
  },
];
